WIP - refining foursquare datasets
MODA-NYC/db-recovery-data-partnership pull request #80
Opened 2020-09-17 15:40 UTC by SPTKL

2020-09-18 16:07 UTC, mgraber requested changes
See updated issue #73:

- [ ] Change table names to something more descriptive (refer to county/zip rather than foursquare/foursquare_datacube)
- [ ] Only use the grouped data -- the only input records should be those where 
```sql 
categoryid = 'Group'
```
- [ ] Remove `state` from foursquare_datacube_grouped
- [ ] Backfilling  a `borough` field and a `borocode` field using the zipcodes
- [ ] Since NYC-only, keep `borough` but remove `county` in foursquare_datacube_grouped (it is empty now)
- [ ] Format `date` as `YYYY-MM-DD` in foursquare and foursquare_grouped

2020-09-18 16:14 UTC, mgraber commented
Also see #82

2020-09-18 21:05 UTC, AmandaDoyle commented on recipes/foursquare/create_county.sql
> +FROM :NAME.:"VERSION" WHERE categoryid != 'Group'
should this be where categoryid == 'Group'?

2020-09-18 21:11 UTC, AmandaDoyle reviewed
Have one question, but no additional comments

2020-09-21 12:43 UTC, mgraber requested changes

2020-09-21 12:43 UTC, mgraber commented on recipes/foursquare/runner.sh
> +TYPE=$1 # datacube/county
`# zipcode/county`

2020-09-21 12:43 UTC, mgraber commented on recipes/foursquare/init.sql
>                  zip as zipcode,
Add borough and borocode to foursquare.weekly_zipcode

2020-09-21 14:59 UTC, mgraber approved these changes

2020-09-21 16:03 UTC, merged