seperating cuebiq from foursquare pr
MODA-NYC/db-recovery-data-partnership pull request #89
Opened 2020-09-17 18:29 UTC by SPTKL

closing #86 to isolate cuebiq

2020-09-18 15:58 UTC, mgraber requested changes
See updates to #72 

- [x] Remove market_area_code and market_area from cuebiq_daily_visits because all records are for NYC market area

2020-09-18 18:33 UTC, mgraber requested changes
I think we can probably remove `market_area_code` and `market_area` from the weekly table for the same reason

2020-09-21 13:34 UTC, SPTKL commented
market_area_code and market_area removed

2020-09-21 15:02 UTC, mgraber approved these changes

2020-09-21 16:03 UTC, merged